### ISSUE TITLE
Fix raster display issues (SLDs) - create and apply the styles manually

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#48]
Most raster layers currently available in the production site use the default styling rules from GeoServer. This way they cannot be previewed properly (thumbnail or WMS preview).

We need to group those layers (by category e.g. all aspect files together) and create custom styles for them.

**Comment by kalxas** [comment]
This will be done with SLD templates

**Comment by kalxas** [comment]
Result preview on beta:
http://2c.terranodo.io/layers/?limit=100&offset=0&type__in=raster

**Comment by schignel** [comment]
1) it looks like the NoData values are showing up as white. Is it possible to have these be blank?

2) the port harcourt elevation map looks like its got some errors in it (or did we already know this?)

3) Steve needs to redo the Aspect SLD so it shows aspect classifications

4) The NDVI_binary .sld should be applied to this layer: http://2c.terranodo.io/layers/geonode:mekelle_ndvi_vegetation2#map=32.25009019234722/4394377.88/1517650.1/0

5) Steve needs to make some edits to the GHSL_DM and GHSL_Confidence legends.

**Comment by kalxas** [comment]
@schignel thanks for the feedback.
1. I will review the templates for nodata values
2. This issue is only in beta site (probably due to some test we did). The production page looks ok http://secondarycities.geonode.state.gov/layers/geonode:por_elevation_30m_srtm#map=87.23050933166155/781513.93/536279.64/0
3. ok, thank you
4. Will apply this style manually on GeoServer for this layer
5. thank you

**Comment by schignel** [comment]
Thanks @kalxas, I'll be sending you the updated .slds shortly. 

Also, I just noticed that it looks like the births layer is missing the pink style: http://2c.terranodo.io/layers/geonode%3Anpl2010adjustedbirths#map=88.94130617305791/9349646.35/3274180.73/0

**Comment by schignel** [comment]
Another strange thing is that it appears that the map shows the red-orange built-up 1975-1990 class at a zoomed out scale, but that it disappears when zoomed in. 

![image](https://user-images.githubusercontent.com/19474876/31143956-6dec96d0-a87f-11e7-8dba-3371424df447.png)

![image](https://user-images.githubusercontent.com/19474876/31143983-80bc791a-a87f-11e7-914a-c256d9841d74.png)

**Comment by schignel** [comment]
Hi @kalxas, I'm attaching the updated styles for Aspect, GHSL_DM, and GHSL_Confidence. These should all be applied exactly as they are (not scaled to min-max), since each of these data types have their own value classes and legends. 

Additionally, we should delete any of aspect layers labeled "[classified](http://2c.terranodo.io/search/?title__icontains=Medellin:%20Aspect%20(classified)&limit=100&offset=0)", since these are no longer necessary.

This should take care of items 3 and 5 from the previous list. 

[Updated_SLDs.zip](https://github.com/state-hiu/2C-GeoNode/files/1353849/Updated_SLDs.zip)

Thanks!
-Steve

**Comment by schignel** [comment]
Hi @kalxas, I also made a .sld for the Contour line vector files (attached). I generated it off of the [10m contour for Cusco](http://2c.terranodo.io/layers/geonode:cus_contour_10m_smoothed_srtm#map=152.8740565703525/-8016336.23/-1537331.57/0). 

I'm not sure if it can be scaled to min-max values for the other contour layers, since these are vector data, but let me know what you think. If we could somehow keep the coloring but just put "Low" and "High" labels in the legend it would still get the point across. 

[Contours.zip](https://github.com/state-hiu/2C-GeoNode/files/1353924/Contours.zip)

![image](https://user-images.githubusercontent.com/19474876/31149617-cb89db5c-a890-11e7-99ea-237df3a6de41.png)

**Comment by kalxas** [comment]
I have applied the correct style for NDVI
http://2c.terranodo.io/layers/geonode:mekelle_ndvi_vegetation2#map=37.99126222393078/4394377.88/1517650.1/0

**Comment by kalxas** [comment]
@schignel for the Aspect SLD I have both "Aspect" and "Aspect_Transformation" in the spreadsheet so I renamed the previous SLD to "Aspect_Transformation". Is that ok?

**Comment by schignel** [comment]
Hi @kalxas I believe those are actually referring to two different layer types. "Aspect" is the regular aspect map (0-360 slope direction) and "Aspect_Transformation" is the TRASP dry-wet [transformation](http://2c.terranodo.io/layers/geonode%3Acus_aspect_transformation_30m_srtm#map=74.35897863280648/-8013515.97/-1521061.82/0) with values from 0-1.

Let me know if that makes sense or if I'm misunderstanding your question.

**Comment by kalxas** [comment]
Since you did not provide 2 slds initially I thought this was a typo....

**Comment by kalxas** [comment]
ok @schignel , I will apply the correct style now and redo the list from the spreadsheet you provided

**Comment by schignel** [comment]
Ok sounds good, thanks!

**Comment by kalxas** [comment]
@schignel new styles are now applied to 2c.terranodo.io, only item left to fix is the no data values.

**Comment by kalxas** [comment]
ok, the no data values were just added.
@schignel please review so we can close this ticket.

**Comment by schignel** [comment]
Thanks @kalxas we can close.
